// Writes docs/CHAMPIONS.md — the 45-champion design book and uniqueness matrix — from the data
// the game actually runs on: shared/champions.js (who, stage, ladder), shared/powers.js (what the
// power does) and public/vfx/ (how it looks and sounds). Generated rather than written by hand
// so it cannot drift from the code; test-vfx.mjs fails when the committed file is stale.
//
//   node scripts/champions-doc.mjs          rewrite docs/CHAMPIONS.md
//   node scripts/champions-doc.mjs --check  exit 1 if it is out of date

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CHAMPIONS, TIERS } from '../shared/champions.js';
import { POWERS } from '../shared/powers.js';
import { VFX, PHASES } from '../public/champ-vfx.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DOC_PATH = path.join(ROOT, 'docs', 'CHAMPIONS.md');

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const stars = (n) => '★'.repeat(Math.floor(n)) + (n % 1 ? '½' : '');
const soundLine = (list) => (list || []).map((n) => {
  const { k, ...o } = n;
  return `${k}(${Object.entries(o).map(([a, b]) => `${a}=${b}`).join(', ')})`;
}).join(' + ');

export function render() {
  const out = [];
  out.push('# The 45 champions');
  out.push('');
  out.push('_Generated by `node scripts/champions-doc.mjs` from shared/champions.js, shared/powers.js and public/vfx/. Do not edit by hand; test-vfx.mjs fails when this file is stale._');
  out.push('');
  out.push('The arcade (שחקן יחיד) is 45 stages, one champion each. Stage *n* is legendary card *n*, and nothing is skipped: beating a stage opens only the next one. The structure comes from Head Soccer\'s arcade, where opponents open one at a time down a fixed list, the difficulty climbs, and every character has its own power. The names, powers, art and sounds here are original.');
  out.push('');
  out.push('Every power uses the ultimate the game already has. Fill the meter, press POWER to arm it, and the next head or body touch of the ball fires the power. The meter is the cooldown: it refills from zero off tackles and play, at the stage\'s `meterRate` for the champion\'s bot. What the power does lives in `shared/powers.js`. How it looks and sounds lives in `public/vfx/tierN.js`, which runs six phases: anticipation, activation, main, impact, aftermath and cleanup (see `public/champ-vfx.js`).');
  out.push('');
  out.push('## Uniqueness matrix');
  out.push('');
  out.push('| # | Champion | Theme | Power | Gameplay effect | Visual language | Counterplay | Difficulty | Shared helpers |');
  out.push('|---|---|---|---|---|---|---|---|---|');
  for (const c of CHAMPIONS) {
    const P = POWERS[c.power], V = VFX[c.power] || {}, d = V.doc || {};
    out.push(`| ${c.stage} | ${cell(c.title)} | ${cell(V.theme)} | ${P.icon} ${cell(P.name)} (\`${P.id}\`) | ${cell(P.desc)} | ${cell(V.visual)} | ${cell(d.counterplay)} | ${stars(c.difficulty.stars)} ${TIERS[c.tier]} | ${cell(d.helpers)} |`);
  }
  out.push('');
  out.push('## The difficulty ladder');
  out.push('');
  out.push('| # | react (s) | misread (px) | aim | counter | aggression | meter rate | jump × | arms |');
  out.push('|---|---|---|---|---|---|---|---|---|');
  for (const c of CHAMPIONS) {
    const D = c.difficulty;
    out.push(`| ${c.stage} | ${D.react} | ${D.error} | ${D.aim} | ${D.counter} | ${D.aggression} | ${D.meterRate} | ${D.body.jump} | ${POWERS[c.power].arm} / ${c.style} |`);
  }
  for (let t = 0; t < TIERS.length; t++) {
    out.push('');
    out.push(`## Tier ${t + 1}: ${TIERS[t]} (stages ${t * 9 + 1}-${t * 9 + 9})`);
    for (const c of CHAMPIONS.filter((x) => x.tier === t)) {
      const P = POWERS[c.power], V = VFX[c.power] || {}, d = V.doc || {}, sq = d.sequence || {};
      out.push('');
      out.push(`### ${c.stage}. ${c.title}: ${P.icon} ${P.name} (\`${P.id}\`)`);
      out.push('');
      out.push(`1. **Champion and theme.** ${c.title}, legendary ${c.stage}. ${V.theme}: ${V.visual}. ${d.fantasy || ''}`);
      out.push(`2. **Power.** ${P.name}: ${P.desc}`);
      out.push(`3. **Gameplay purpose.** ${d.purpose || ''}`);
      out.push(`4. **Activation, duration, cooldown.** Kind \`${P.kind}\`, lasts ${P.duration ? P.duration + 's' : 'the one shot'}. Armed with a full meter, fired by the next head or body touch. The meter must refill before the next use.`);
      out.push(`5. **Player behaviour.** ${d.player || ''}`);
      out.push(`6. **Bot behaviour.** ${d.bot || ''} Ladder: react ${c.difficulty.react}s, aim ${c.difficulty.aim}, arms after ${c.difficulty.powerHold}s on a full meter, arm moment \`${P.arm}\`, style \`${c.style}\`.`);
      out.push('7. **Visual sequence.**');
      for (const ph of PHASES) out.push(`   - *${ph}*: ${sq[ph] || ''}`);
      out.push(`8. **Particles, objects, trails, lighting, camera.** ${d.layers || ''} Camera: ${d.camera || ''}`);
      out.push(`9. **HUD and cooldown.** ${d.hud || ''}`);
      out.push(`10. **Audio hooks.** ${d.audio || ''} Fire: \`${soundLine(V.sounds?.fire)}\`. Impact: \`${soundLine(V.sounds?.impact)}\`. End: \`${soundLine(V.sounds?.end)}\`.`);
      out.push(`11. **Counterplay.** ${d.counterplay || ''}`);
      out.push(`12. **Performance.** ${d.perf || ''}`);
      out.push(`13. **Systems and helpers used.** ${d.helpers || ''}`);
    }
  }
  out.push('');
  return out.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const text = render();
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(DOC_PATH) ? fs.readFileSync(DOC_PATH, 'utf8') : '';
    if (cur !== text) { console.log('docs/CHAMPIONS.md is stale — run node scripts/champions-doc.mjs'); process.exit(1); }
    console.log('docs/CHAMPIONS.md is current');
  } else {
    fs.writeFileSync(DOC_PATH, text);
    console.log(`wrote ${path.relative(ROOT, DOC_PATH)} (${text.length} bytes)`);
  }
}
