// Writes docs/CHAMPIONS.md — the 45 arcade champions as the game actually runs them — from
// shared/champions.js (who, stage, ladder, HS stats) and shared/hs-powers.js (what each shot family,
// ailment and aura does). It also regenerates shared/hs-champion-map.js from the approved
// docs/hs-champion-map.json, because the server only serves public/ and shared/ and a phone cannot
// fetch docs/. Generated rather than written by hand so neither can drift from the code;
// test-vfx.mjs fails when CHAMPIONS.md is stale and test-hs-champion-map.mjs when the module is.
//
//   node scripts/champions-doc.mjs          rewrite both
//   node scripts/champions-doc.mjs --check  exit 1 if either is out of date

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CHAMPIONS, TIERS } from '../shared/champions.js';
import { FAMILIES, AILMENTS, HS, statsFor, meterRateFor, ailDur } from '../shared/hs-powers.js';
import * as C from '../shared/constants.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DOC_PATH = path.join(ROOT, 'docs', 'CHAMPIONS.md');
export const MAP_JSON = path.join(ROOT, 'docs', 'hs-champion-map.json');
export const MAP_MODULE = path.join(ROOT, 'shared', 'hs-champion-map.js');

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
const stars = (n) => '★'.repeat(Math.floor(n)) + (n % 1 ? '½' : '');
const r2 = (v) => Math.round(v * 100) / 100;

// What each family does, in a line — the same rules shared/hs-powers.js runs.
const FAMILY_TEXT = {
  straight: 'The filmed comet: dead flat at the goal at POWER_SHOT_SPEED (HS M4, 2150 px/s).',
  ground: 'Drops to the turf and rolls along it. Cannot be blocked: a kick does not stop it; it trips whoever it meets and rolls on. Only a counter answers it.',
  downward: 'A short hop up, then a straight line down into the foot of the goal.',
  destructive: 'A slower, heavy straight shot that smashes a kick-block aside and rolls on.',
  aerial: `Straight up and off the top of the screen, ~${HS.AERIAL_WAIT}s of warning streaks, then a dive at ${HS.AERIAL_DIVE_DEG}° into the goal mouth (HS M2).`,
  delay: `Flies a beat (${HS.DELAY_GO}s), hangs dead in the air for 0.45–1.2s by intensity, then bursts on at the goal.`,
  grab: 'A claw that seizes a defender who does not kick it and carries him toward his own goal (HS M3), then flies on. Gentle (stage 2): a third of the way, and a jump breaks it.',
  multiball: 'The shot plus one or two extra power balls fanned off it, any of which may score. Gentle (stage 6): one extra at 70% pace.',
  updown: 'Rises and falls as it flies (a literal sine table, so every phone flies the same wave).',
  ailment: 'A curse shot whose point is its ailment, which lands even through a block and lasts 1.4× as long.',
  critical: 'The fastest shot (1.3×). It goes through a kick-block at full pace; only a counter stops it.',
};
const AIL_TEXT = {
  reverse: 'left and right swapped (???)', shock: 'half speed, no jump, no dash', freeze: 'frozen in ice, no control',
  beheaded: 'no head: no header, the ball passes where it was', burn: 'cannot kick, 0.8× speed', stars: 'dazed, no control',
};
const AURA_TEXT = {
  none: '—', stun: `stuns (${HS.AURA_STUN}s, stars)`, push: `pushes away (${HS.AURA_PUSH} px/s)`,
  reverse: `reverses controls (${HS.AURA_REVERSE}s)`, freeze: `freezes (${HS.AURA_FREEZE}s)`,
};

export function render() {
  const out = [];
  out.push('# The 45 champions');
  out.push('');
  out.push('_Generated by `node scripts/champions-doc.mjs` from shared/champions.js and shared/hs-powers.js (the approved map is docs/HS-CHAMPION-MAP.md). Do not edit by hand; test-vfx.mjs fails when this file is stale._');
  out.push('');
  out.push('The arcade (שחקן יחיד) is 45 stages, one champion each. Stage *n* is legendary card *n*, and beating a stage opens only the next one. Every champion is a Head Soccer power shot and nothing else: a **family** (how the ball flies), an optional **ailment** (what it leaves on the player it hits), an **aura** (what pressing POWER does to an opponent within the radius), HS\'s five 1–10 **stats** and a star rating. The names, art and sounds are original.');
  out.push('');
  out.push('How a power shot plays (docs/HS-POWER-SHOTS.md): fill the gauge, press POWER to arm (the player crackles gold), and the next head or body touch of the ball fires the shot. The screen darkens for 1.34s round the shooter; the ball leaves 0.97s in and flies under the dark. When it reaches the other player: **armed** → he counters it with his own shot; **kicking** → he blocks it (0.8s grinding on the boot, 0.4s dead, then it fires back as his); **otherwise** → he is knocked back into his net with it, dazed 0.5s with three stars, and the ailment lands. Online, every card fires its family at the same middle intensity on equal stats.');
  out.push('');
  out.push('## The families');
  out.push('');
  out.push('| Family | Speed × | A kick into it | What it does |');
  out.push('|---|---|---|---|');
  const BLOCK = { grind: 'blocks it', none: 'does nothing', smash: 'is smashed aside', through: 'is gone through', grab: 'blocks the claw' };
  for (const [id, F] of Object.entries(FAMILIES)) out.push(`| ${F.en} (${F.name}) | ${F.speed} | ${BLOCK[F.block]} | ${cell(FAMILY_TEXT[id])} |`);
  out.push('');
  out.push('## The champions');
  out.push('');
  out.push('| # | Tier | Champion | Theme | Family | Ailment | Aura (radius) | Intensity | Stats S/J/K/D/P | Body × (speed/jump/kick) | Gauge × | ★ |');
  out.push('|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const c of CHAMPIONS) {
    const h = c.hs, s = h.stats, b = statsFor(s);
    const ail = h.ailment ? `${h.ailment} (${r2(ailDur(h.ailment, h.intensity, h.family))}s)` : '—';
    const aura = h.aura === 'none' ? '—' : `${h.aura} (${h.auraRadius}px)`;
    out.push(`| ${c.stage} | ${TIERS[c.tier]} | ${cell(c.title)} | ${c.icon} ${cell(c.powerName)} | ${FAMILIES[h.family].en}${h.gentle ? ' (gentle)' : ''} | ${ail} | ${aura} | ${h.intensity} | ${s.speed}/${s.jump}/${s.kick}/${s.dash}/${s.power} | ${r2(b.speed)}/${r2(b.jump)}/${r2(b.kick)} | ${r2(meterRateFor(s.power))} | ${stars(h.stars)} |`);
  }
  out.push('');
  out.push('## Ailments and auras');
  out.push('');
  out.push('| Ailment | Effect | Base duration |');
  out.push('|---|---|---|');
  for (const [id, A] of Object.entries(AILMENTS)) out.push(`| ${id} (${A.name}) | ${AIL_TEXT[id]} | ${A.dur}s at intensity 0.5 (×0.6–1.4 with intensity) |`);
  out.push('');
  out.push('| Aura | On the press, an opponent within the radius |');
  out.push('|---|---|');
  for (const [id, t] of Object.entries(AURA_TEXT)) out.push(`| ${id} | ${t} |`);
  out.push('');
  out.push('## The bot ladder');
  out.push('');
  out.push('| # | react (s) | misread (px) | aim | counter | aggression | arms after (s) | style |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (const c of CHAMPIONS) {
    const D = c.difficulty;
    out.push(`| ${c.stage} | ${D.react} | ${D.error} | ${D.aim} | ${D.counter} | ${D.aggression} | ${D.powerHold} | ${c.style} |`);
  }
  out.push('');
  out.push(`_Power-shot constants: POWER_SHOT_SPEED ${C.POWER_SHOT_SPEED} px/s, POWER_CUTIN ${C.POWER_CUTIN}s (the ball leaves ${r2(C.POWER_CUTIN - C.POWER_RELEASE)}s in), POWER_BLOCK_STUN ${C.POWER_BLOCK_STUN}s, block grind ${HS.BLOCK_GRIND}s + ${HS.BLOCK_REST}s._`);
  out.push('');
  return out.join('\n');
}

// shared/hs-champion-map.js, from the approved JSON: only the fields the game reads.
export function renderMap() {
  const rows = JSON.parse(fs.readFileSync(MAP_JSON, 'utf8')).sort((a, b) => a.stage - b.stage).map((r) => ({
    stage: r.stage, id: r.id, family: r.family, ailment: r.ailment, aura: r.aura, auraRadius: r.auraRadius,
    intensity: r.intensity, gentle: !!r.gentle, profile: r.profile, stats: r.stats, stars: r.stars, power: r.power,
  }));
  return '// GENERATED from docs/hs-champion-map.json by scripts/champions-doc.mjs — do not edit by hand.\n'
    + '// The approved Head Soccer mapping of the 45 arcade champions (docs/HS-CHAMPION-MAP.md), as a\n'
    + '// module, because the server only serves public/ and shared/ and a phone cannot fetch docs/.\n'
    + '// test-hs-champion-map.mjs fails if this and the JSON ever disagree.\n'
    + 'export const HS_MAP = Object.freeze([\n'
    + rows.map((r) => '  ' + JSON.stringify(r)).join(',\n') + ',\n'
    + '].map((r) => Object.freeze(r)));\n';
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const files = [[DOC_PATH, render()], [MAP_MODULE, renderMap()]];
  if (process.argv.includes('--check')) {
    let bad = 0;
    for (const [f, text] of files) {
      const cur = fs.existsSync(f) ? fs.readFileSync(f, 'utf8') : '';
      if (cur !== text) { console.log(`${path.relative(ROOT, f)} is stale — run node scripts/champions-doc.mjs`); bad++; }
    }
    if (bad) process.exit(1);
    console.log('docs/CHAMPIONS.md and shared/hs-champion-map.js are current');
  } else {
    for (const [f, text] of files) { fs.writeFileSync(f, text); console.log(`wrote ${path.relative(ROOT, f)} (${text.length} bytes)`); }
  }
}
